name: ci

on: [ push, pull_request ]

jobs:
  inspection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install flake8
      - run: pip install mypy
      - run: flake8 run.py sinner
      - run: mypy --config-file mypy.ini run.py sinner
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install -r requirements-ci.txt
      - run: pytest -m "not skip"

